version: '3.2'

services:
  php:
    build:
      context: docker/php
    container_name: $PHP_CONTAINER_NAME
    working_dir: /var/www/html
    volumes:
      - ./web:/var/www/html
      - .env:/var/www/.env
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
  nginx:
    build: ./docker/nginx/
    container_name: $NGINX_CONTAINER_NAME
    restart: always
    ports:
      - "${NGINX_EXPOSE_PORT}:${NGINX_PORT}"
    volumes:
      - ./web:/var/www/html:ro
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
